openapi: "3.0.3"
info:
  title: Bonfire API GUide
  version: "0.1"
  contact:
    email: diplomarbeit.sma@gmail.com
servers:
  - url: http://localhost:3000/
  - url: https://backend-module.onrender.com
tags:
  - name: authentication
    description: user authentication
components:
  schemas:
    LoginSchema:
      type: object
      properties:
        userName:
          type: string
          default: "Max"
        password:
          type: string
    SignUpSchema:
      type: object
      properties:
        firstName:
          type: string
          default: "Max"
        lastName:
          type: string
          default: "Mustermann"
        userName:
          type: string
          default: "maxmusstermann"
        email:
          type: string
          default: "max@mustermann.com"
        password:
          type: string
        dateOfBirth:
          type: string
          default: "2000-01-01"
    Error:
      type: object
      properties:
        error:
          type: boolean
        statusCode:
          type: integer
        message:
          type: string
        name:
          type: string
    Tokens:
      type: object
      properties:
        refresh:
          type: string
        access:
          type: string
paths:
  /auth/login:
    post:
      tags:
        - authentication
      description: Used for login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginSchema"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Tokens"
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Error"
        "500":
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Error"
  /auth/signup:
    post:
      tags:
        - authentication
      description: For user registration used
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpSchema"
      responses:
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Tokens"
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Error"
        "500":
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Error"
