name: Lines of Code
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
      - name: Calculate Lines of Code
        id: loc
        uses: PavanMudigonda/lines-of-code-reporter@v1.5
        with:
          directory: "./src/, ./tests/"
          include_ext: "ts,js"                      
          exclude_dir: "node_modules,.github, ./prisma/migrations, ./logs/, ./dist"       
          exclude_ext: "ps1,go,sh"                  

      - name: Add Lines of Code Summary
        run: echo "${{ steps.loc.outputs.lines-of-code-summary }}" >> $GITHUB_STEP_SUMMARY

      - name: print output
        shell: pwsh
        run: | 
          Write-Host 'Total Lines of Code...:  ${{ steps.loc.outputs.total_lines }}'
          Write-Host 'Lines of Code Markdown Report Path...:  ${{ steps.loc.outputs.loc_report }}' 
                    